name: PowerShell checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  static-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run static tests
        shell: powershell
        run: .\\tests\\Test-Static.ps1

